### ISSUE TITLE
Can't Compile For Linux & Replacing app doesn't work...

### ISSUE THREAD

**Issue by Geyup** [P-T-C/Popcorn-Time-Community#1]
Hi,

I was told these are the source fixes and when I use this ```app``` directory and I try to compile popcorn-time in Linux the source is still trying to look for ```git.popcorntime.io```

Also if I unpack package.nw and replace the app directory with this one and I start Popcorn-Time it fails to load the movies, also the TV section doesn't show the new URL, I still see the old one; 

https://eztvapi.re/

This is what I see at the terminal when I run Popcorn-Time;

[10176:1110/205322:INFO:CONSOLE(48)] ""[%cWARNING%c] YTS API endpoint '%s' failed." "color: orange;" "color: black;" "https://yts.to/"", source: app://host/src/app/app.js (48)

It still trys to load YTS for the movies. hmm

We still need a fix for Linux...

thanks

**Comment by lesion** [comment]
It's working on linux, just tried!!!! 
try to checkout again
